/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fahh;

/**
 *
 * @author User
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        LoginButton = new javax.swing.JMenu();
        DataButton = new javax.swing.JMenu();
        DataMobilButton = new javax.swing.JMenuItem();
        DataPembeliButton = new javax.swing.JMenuItem();
        DataPaketButton = new javax.swing.JMenuItem();
        DataBayarCashButton = new javax.swing.JMenuItem();
        DataKredit = new javax.swing.JMenuItem();
        DataBayarCicilan = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        PenjualanCashButton = new javax.swing.JMenuItem();
        PenjualanKreditButton = new javax.swing.JMenuItem();
        StatusCicilanButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome, User");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        LoginButton.setText("Login");
        jMenuBar2.add(LoginButton);

        DataButton.setText("Data");

        DataMobilButton.setText("Data Mobil");
        DataMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataMobilButtonActionPerformed(evt);
            }
        });
        DataButton.add(DataMobilButton);

        DataPembeliButton.setText("Data Pembeli");
        DataButton.add(DataPembeliButton);

        DataPaketButton.setText("Data Paket");
        DataPaketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPaketButtonActionPerformed(evt);
            }
        });
        DataButton.add(DataPaketButton);

        DataBayarCashButton.setText("Data Bayar Cash");
        DataBayarCashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBayarCashButtonActionPerformed(evt);
            }
        });
        DataButton.add(DataBayarCashButton);

        DataKredit.setText("Data Kredit");
        DataButton.add(DataKredit);

        DataBayarCicilan.setText("Data Bayar Cicilan");
        DataButton.add(DataBayarCicilan);

        jMenuBar2.add(DataButton);

        jMenu6.setText("Laporan");

        PenjualanCashButton.setText("Penjualan Cash");
        PenjualanCashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanCashButtonActionPerformed(evt);
            }
        });
        jMenu6.add(PenjualanCashButton);

        PenjualanKreditButton.setText("Penjualan Kredit");
        PenjualanKreditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanKreditButtonActionPerformed(evt);
            }
        });
        jMenu6.add(PenjualanKreditButton);

        StatusCicilanButton.setText("Status Cicilan");
        StatusCicilanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusCicilanButtonActionPerformed(evt);
            }
        });
        jMenu6.add(StatusCicilanButton);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataMobilButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataMobilButtonActionPerformed

    private void DataBayarCashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBayarCashButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataBayarCashButtonActionPerformed

    private void PenjualanCashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanCashButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenjualanCashButtonActionPerformed

    private void PenjualanKreditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanKreditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenjualanKreditButtonActionPerformed

    private void StatusCicilanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusCicilanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusCicilanButtonActionPerformed

    private void DataPaketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPaketButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataPaketButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DataBayarCashButton;
    private javax.swing.JMenuItem DataBayarCicilan;
    private javax.swing.JMenu DataButton;
    private javax.swing.JMenuItem DataKredit;
    private javax.swing.JMenuItem DataMobilButton;
    private javax.swing.JMenuItem DataPaketButton;
    private javax.swing.JMenuItem DataPembeliButton;
    private javax.swing.JMenu LoginButton;
    private javax.swing.JMenuItem PenjualanCashButton;
    private javax.swing.JMenuItem PenjualanKreditButton;
    private javax.swing.JMenuItem StatusCicilanButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
