/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fahh;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author User
 */
public class LaporanJualCash extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    Koneksi k = new Koneksi();
    public LaporanJualCash() {
        initComponents();
        k.connect();
    }
    public void ShowData(){
        try{
            String pilihan=PilihanLaporan.getSelectedItem().toString();
            DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            String sql="select bc.kode_cash,p.nama_pembeli,"+"concat(m.merk,'',m.type) as mobil,"+"m.harga,bc.cash_tgl,bc.cash_bayar "+"from beli_cash bc "+"join pembeli p on bc.ktp=p.ktp "+"join mobil m on bc.kode_mobil=m.kode_mobil ";
            if("Harian".equals(pilihan)){
                Date date=Periode.getDate();
                String tgl=df.format(date);
                sql+="where bc.cash_tgl='"+tgl+"'";
            }else if("Mingguan".equals(pilihan)){
                Date awal=TanggalAwal.getDate();
                Date akhir=TanggalAkhir.getDate();
                String tglawal=df.format(awal);
                String tglakhir=df.format(akhir);
                sql+="where bc.cash_tgl between'"+tglawal+"' and '"+tglakhir+"'";
            }else if("Bulanan".equals(pilihan)){
                Date date =Periode.getDate();
                DateFormat bln=new SimpleDateFormat("MM");
                DateFormat thn=new SimpleDateFormat("yyyy");
                String bulan=bln.format(date);
                String tahun=thn.format(date);
                sql+="where month(bc.cash_tgl)="+bulan+" and year (bc.cash_tgl)="+tahun;
            }else if("Tahunan".equals(pilihan)){
                Date date=Periode.getDate();
                DateFormat thn=new SimpleDateFormat("yyyy");
                String tahun=thn.format(date);
                sql+="where year(bc.cash_tgl)="+tahun;
            }
            
            stat=k.getCon().prepareStatement(sql);
            rs=stat.executeQuery();
            model=new DefaultTableModel(new String[]{
                "Kode Cash","Nama Pembeli","Merk dan Tipe Mobil","Harga Mobil","Tanggal","Jumlah Bayar"
            },0);
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("kode_cash"),
                    rs.getString("nama_pembeli"),
                    rs.getString("mobil"),
                    rs.getLong("harga"),
                    rs.getDate("cash_tgl"),
                    rs.getLong("cash_bayar")
                });
            }
            TabelLaporanJualCash.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error menampilkan data!"+e.getMessage());
            e.printStackTrace();
        }
    }
    public void ComboKredit(){
    try{
            this.stat=k.getCon().prepareStatement("select * from kredit");
            this.rs=this.stat.executeQuery();
            while(rs.next()){
                    PilihanLaporan.addItem(rs.getString("kode_kredit")+":"
                    +rs.getString("ktp")+":"
                    +rs.getString("kode_paket")+":"
                    +rs.getString("kode_mobil")+":"
                    +rs.getString("tanggal_kredit")+":"
                    +rs.getString("bayar_kredit")+":"
                    +rs.getString("tenor")+":"
                    +rs.getString("totalcicil")+":"
                    );
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLaporanJualCash = new javax.swing.JTable();
        KembaliButton = new javax.swing.JLabel();
        TampilkanLaporan = new javax.swing.JLabel();
        PilihanLaporan = new javax.swing.JComboBox<>();
        TanggalAkhir = new com.toedter.calendar.JDateChooser();
        Periode = new com.toedter.calendar.JDateChooser();
        TanggalAwal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Laporan Penjualan Cash");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pilihan Laporan:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Periode:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 80, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Pilihan Laporan:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 90, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tanggal Awal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 80, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tanggal Akhir:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 110, 20));

        TabelLaporanJualCash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelLaporanJualCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelLaporanJualCashMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelLaporanJualCash);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 517, 950, 270));

        KembaliButton.setBackground(new java.awt.Color(51, 51, 255));
        KembaliButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KembaliButton.setText("Kembali");
        KembaliButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliButtonMouseClicked(evt);
            }
        });
        getContentPane().add(KembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TampilkanLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TampilkanLaporan.setText("Tampilkan Laporan");
        TampilkanLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TampilkanLaporanMouseClicked(evt);
            }
        });
        getContentPane().add(TampilkanLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 110, 20));

        PilihanLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harian", "Mingguan", "Bulanan", "Tahunan" }));
        getContentPane().add(PilihanLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, -1));
        getContentPane().add(TanggalAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 130, -1));
        getContentPane().add(Periode, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 130, -1));
        getContentPane().add(TanggalAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliButtonMouseClicked
        // TODO add your handling code here:
        new Beranda().show();
        this.dispose();
    }//GEN-LAST:event_KembaliButtonMouseClicked

    private void TabelLaporanJualCashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelLaporanJualCashMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_TabelLaporanJualCashMouseClicked

    private void TampilkanLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TampilkanLaporanMouseClicked
        // TODO add your handling code here:
        ShowData();
    }//GEN-LAST:event_TampilkanLaporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanJualCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanJualCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanJualCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanJualCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanJualCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KembaliButton;
    private com.toedter.calendar.JDateChooser Periode;
    private javax.swing.JComboBox<String> PilihanLaporan;
    private javax.swing.JTable TabelLaporanJualCash;
    private javax.swing.JLabel TampilkanLaporan;
    private com.toedter.calendar.JDateChooser TanggalAkhir;
    private com.toedter.calendar.JDateChooser TanggalAwal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
