/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fahh;

/**
 *
 * @author User
 */
public class MenuDataPembeli extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public MenuDataPembeli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        HapusButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NoKTP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NamaPembeli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AlamatPembeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NoHP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPembeli = new javax.swing.JTable();
        KembaliButton = new javax.swing.JLabel();
        TambahButton = new javax.swing.JLabel();
        EditButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Halaman Data Pembeli");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        HapusButton.setBackground(new java.awt.Color(51, 51, 255));
        HapusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HapusButton.setText("Hapus");
        getContentPane().add(HapusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("No KTP:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, 20));

        NoKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoKTPActionPerformed(evt);
            }
        });
        getContentPane().add(NoKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 600, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nama Pembeli:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 90, 20));

        NamaPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(NamaPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 600, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Alamat Pembeli:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, 20));

        AlamatPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(AlamatPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 600, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("No HP:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, 20));

        NoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoHPActionPerformed(evt);
            }
        });
        getContentPane().add(NoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 600, -1));

        TabelPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelPembeli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 950, -1));

        KembaliButton.setBackground(new java.awt.Color(51, 51, 255));
        KembaliButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KembaliButton.setText("Kembali");
        KembaliButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliButtonMouseClicked(evt);
            }
        });
        getContentPane().add(KembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TambahButton.setBackground(new java.awt.Color(51, 51, 255));
        TambahButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TambahButton.setText("Tambah");
        getContentPane().add(TambahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        EditButton.setBackground(new java.awt.Color(51, 51, 255));
        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditButton.setText("Edit");
        getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoKTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoKTPActionPerformed

    private void NamaPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPembeliActionPerformed

    private void AlamatPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatPembeliActionPerformed

    private void NoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoHPActionPerformed

    private void KembaliButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliButtonMouseClicked
        // TODO add your handling code here:
        new Beranda().show();
        this.dispose();
    }//GEN-LAST:event_KembaliButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDataPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDataPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDataPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDataPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDataPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatPembeli;
    private javax.swing.JLabel EditButton;
    private javax.swing.JLabel HapusButton;
    private javax.swing.JLabel KembaliButton;
    private javax.swing.JTextField NamaPembeli;
    private javax.swing.JTextField NoHP;
    private javax.swing.JTextField NoKTP;
    private javax.swing.JTable TabelPembeli;
    private javax.swing.JLabel TambahButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
