/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fahh;

/**
 *
 * @author User
 */
public class MenuDataBayarCicilan extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public MenuDataBayarCicilan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        HapusButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JumlahCicilan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBayarCicilan = new javax.swing.JTable();
        KembaliButton = new javax.swing.JLabel();
        TambahButton = new javax.swing.JLabel();
        EditButton = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SisaHarga = new javax.swing.JTextField();
        KodeKredit = new javax.swing.JComboBox<>();
        TanggalCicilan = new com.toedter.calendar.JDateChooser();
        KodeCicilan = new javax.swing.JTextField();
        CicilanKe = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Halaman Data Bayar Cicilan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        HapusButton.setBackground(new java.awt.Color(51, 51, 255));
        HapusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HapusButton.setText("Hapus");
        getContentPane().add(HapusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Kode Cicilan:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, 20));

        JumlahCicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahCicilanActionPerformed(evt);
            }
        });
        getContentPane().add(JumlahCicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 570, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Kode Kredit:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 80, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Cicilan ke-:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 70, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Jumlah Cicilan:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Sisa Harga:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 110, 20));

        TabelBayarCicilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelBayarCicilan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 950, -1));

        KembaliButton.setBackground(new java.awt.Color(51, 51, 255));
        KembaliButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KembaliButton.setText("Kembali");
        KembaliButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliButtonMouseClicked(evt);
            }
        });
        getContentPane().add(KembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TambahButton.setBackground(new java.awt.Color(51, 51, 255));
        TambahButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TambahButton.setText("Tambah");
        getContentPane().add(TambahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        EditButton.setBackground(new java.awt.Color(51, 51, 255));
        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditButton.setText("Edit");
        getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tanggal Cicilan:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, 20));

        SisaHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SisaHargaActionPerformed(evt);
            }
        });
        getContentPane().add(SisaHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 570, -1));

        KodeKredit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(KodeKredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 570, -1));
        getContentPane().add(TanggalCicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 570, -1));

        KodeCicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeCicilanActionPerformed(evt);
            }
        });
        getContentPane().add(KodeCicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 570, -1));

        CicilanKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CicilanKeActionPerformed(evt);
            }
        });
        getContentPane().add(CicilanKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 570, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JumlahCicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahCicilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahCicilanActionPerformed

    private void SisaHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SisaHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SisaHargaActionPerformed

    private void KodeCicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeCicilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeCicilanActionPerformed

    private void CicilanKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CicilanKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CicilanKeActionPerformed

    private void KembaliButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliButtonMouseClicked
        // TODO add your handling code here:
        new Beranda().show();
        this.dispose();
    }//GEN-LAST:event_KembaliButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDataBayarCicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDataBayarCicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDataBayarCicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDataBayarCicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDataBayarCicilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CicilanKe;
    private javax.swing.JLabel EditButton;
    private javax.swing.JLabel HapusButton;
    private javax.swing.JTextField JumlahCicilan;
    private javax.swing.JLabel KembaliButton;
    private javax.swing.JTextField KodeCicilan;
    private javax.swing.JComboBox<String> KodeKredit;
    private javax.swing.JTextField SisaHarga;
    private javax.swing.JTable TabelBayarCicilan;
    private javax.swing.JLabel TambahButton;
    private com.toedter.calendar.JDateChooser TanggalCicilan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
