/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fahh;

/**
 *
 * @author User
 */
public class MenuDataBeliCash extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public MenuDataBeliCash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        HapusButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KodeCash = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBeliCash = new javax.swing.JTable();
        KembaliButton = new javax.swing.JLabel();
        TambahButton = new javax.swing.JLabel();
        EditButton = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Bayar = new javax.swing.JTextField();
        KTPPembeli = new javax.swing.JComboBox<>();
        KodeMobil = new javax.swing.JComboBox<>();
        TanggalPembelian = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Transaksi Beli Cash");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        HapusButton.setBackground(new java.awt.Color(51, 51, 255));
        HapusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HapusButton.setText("Hapus");
        getContentPane().add(HapusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Kode Cash:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, 20));

        KodeCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeCashActionPerformed(evt);
            }
        });
        getContentPane().add(KodeCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 570, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("KTP Pembeli:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 80, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kode Mobil:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 70, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tanggal Pembelian:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 20));

        TabelBeliCash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelBeliCash);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 950, -1));

        KembaliButton.setBackground(new java.awt.Color(51, 51, 255));
        KembaliButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KembaliButton.setText("Kembali");
        KembaliButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliButtonMouseClicked(evt);
            }
        });
        getContentPane().add(KembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TambahButton.setBackground(new java.awt.Color(51, 51, 255));
        TambahButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TambahButton.setText("Tambah");
        getContentPane().add(TambahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        EditButton.setBackground(new java.awt.Color(51, 51, 255));
        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditButton.setText("Edit");
        getContentPane().add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Bayar(RP):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 110, 20));

        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });
        getContentPane().add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 570, -1));

        KTPPembeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(KTPPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 570, -1));

        KodeMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(KodeMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 570, -1));
        getContentPane().add(TanggalPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 570, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KodeCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeCashActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarActionPerformed

    private void KembaliButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliButtonMouseClicked
        // TODO add your handling code here:
        new Beranda().show();
        this.dispose();
    }//GEN-LAST:event_KembaliButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDataBeliCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDataBeliCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDataBeliCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDataBeliCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDataBeliCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bayar;
    private javax.swing.JLabel EditButton;
    private javax.swing.JLabel HapusButton;
    private javax.swing.JComboBox<String> KTPPembeli;
    private javax.swing.JLabel KembaliButton;
    private javax.swing.JTextField KodeCash;
    private javax.swing.JComboBox<String> KodeMobil;
    private javax.swing.JTable TabelBeliCash;
    private javax.swing.JLabel TambahButton;
    private com.toedter.calendar.JDateChooser TanggalPembelian;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
